### ISSUE TITLE
Invalid MPD generation 

### ISSUE THREAD

**Issue by solaris7x** [google/shaka-streamer#58] opened 2020-06-01 06:25 UTC
Issue: 
mpd files generated could not be played 
The player incorrectly assumes the provided mpd is live whereas the mpd is meant to be VOD

Note: 
HLS files generated with same do work on [Bitmovin](https://bitmovin.com/demos/stream-test) & [Akamai](https://players.akamai.com/players/dashjs) player 
Couldn't get HLS to play on shaka-player demo , error 4015 

[Dash validator](https://conformance.dashif.org/) reports invalid Representation 

Base OS: Ubuntu 18.04 LTS amd64
Shaka streamer installed with `pip3 install --upgrade shaka-streamer`
FFmpeg custom built with flags in shaka-streamer tutorial:
Link: ***Removed URL***
`ffmpeg version n4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --enable-libx264 --enable-libvpx --enable-libopus --enable-gpl --enable-libfreetype --enable-libfontconfig --enable-nvenc
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100`

I have attached the files generated with original and config used
Dolby Leaf Sample : ***Removed URL***
Sintel MPD only ***Removed URL*** (Sintel original not being attached as it was too big but can fetched from link in input config)
Very small output ***Removed URL***
I also tried to host these files on a hacky express server (Range Header supported)
Dolby Leaf Sample HLS:  ***Removed URL***
Dolby Leaf Sample DASH: ***Removed URL***
Sintel MPD only: ***Removed URL***

Thank you for your time , I suspect this issue to be caused my incorrect config or ffmpeg build but I have rebuilt it several time on different machines but the result being same 
Also tried hosting files locally using expressjs static but the results being same 
Please Note the above mentioned drive and heroku links are for testing purposes and may not always work , in such case please contact me

Edit : Removed Hosted files due to lack of interaction , can mail or share files if needed

**Comment by solaris7x** [comment] 2020-06-03 04:49
I tried to manually transcode the dolby leaf sample with same ffmpeg as above according to shaka packager tutorial and generate the mpd with packager , the mpd file seems to be working , If the above issue is due to my lack of knowledge / bad config , I do hope someone can enlighten me as I don't know which part is causing the issue

**Comment by joeyparrish** [comment] 2020-08-17 19:03
#61 appears to be similar enough that I suspect they share a root cause.  I'm going to close this issue as a duplicate, even though it came first, because the other has more details (config snippets and MPD output snippet) that should be useful in debugging.

**Closed** 2020-08-17 19:03 UTC
Labels: bug, duplicate
